sudo: required
language: generic

services:
  - docker
before_install:
  - docker build -t 2553/marvis_sms_test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true 2553/marvis_sms_test npm test

after_success:
  - docker build -t 2553/marvis_sms_client ./client
  - docker build -t 2553/marvis_sms_nginx ./nginx
  - docker build -t 2553/marvis_sms_server ./server
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take images and push to docker hub
  - docker push 2553/marvis_sms_client
  - docker push 2553/marvis_sms_nginx
  - docker push 2553/marvis_sms_server
